[package]
edition = "2021"
name = "membrane_proof"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "membrane_proof"

[dependencies]
serde = "1"
derive_more = "0"

hdi = { workspace = true }
